routes/web.php
<?php

use App\Http\Controllers\HeroController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn() => redirect()->route('heroes.index'));

Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'heroes', 'as' => 'heroes.'], function () {
        Route::get('', [HeroController::class, 'index'])->name('index');
        Route::patch('{id}', [HeroController::class, 'update'])->name('update');
        Route::get('{hero}', [HeroController::class, 'get'])->name('get');
        Route::get('{hero}/edit', [HeroController::class, 'edit'])->name('edit');
    });
});

require __DIR__.'/auth.php';

app/Models/Hero.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hero extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'height',
        'mass',
        'hair_color',
        'hair_color',
        'birth_year',
        'gender',
    ];

    public function isMale(): bool
    {
        return $this->gender === 'male';
    }

    public function isFemale(): bool
    {
        return $this->gender === 'female';
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HeroController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\HeroUpdateRequest;
use App\Models\Hero;
use App\Services\HeroServiceInterface;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class HeroController extends Controller
{
    public function __construct(
        private HeroServiceInterface $heroService,
    ) {
    }

    public function index(): View
    {
        return view('heroes.index');
    }

    public function get(Hero $hero): View
    {
        return view('heroes.get', ['hero' => $hero]);
    }

    public function edit(Hero $hero): View
    {
        return view('heroes.edit', ['hero' => $hero]);
    }

    public function update(HeroUpdateRequest $request, int $id): RedirectResponse
    {
        $this->heroService->update($id, $request->validated());

        return back()->with('status', 'Hero has been updated!');
    }
}

app/Http/Livewire/HeroesTable.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Hero;
use App\Services\HeroServiceInterface;
use Livewire\Component;
use Livewire\WithPagination;

class HeroesTable extends Component
{
    use WithPagination;

    public string $name = '';
    public string $gender = 'all';

    protected $queryString = [
        'name' => ['except' => ''],
        'gender' => ['except' => 'all']];

    public function updatingName()
    {
        $this->resetPage();
    }

    public function updatingGender()
    {
        $this->resetPage();
    }

    public function render(HeroServiceInterface $heroService)
    {
        $heroes = $heroService->filterAndPaginate($this->name, $this->gender);
        $genders = $heroService->getGenders();

        return view('livewire.heroes-table', ['heroes' => $heroes, 'genders' => $genders]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/heroes/edit.blade.php
<x-app-layout>
    @section('title')
        {{ $hero->name }}
    @endsection

    <div class="py-3 md:py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if (session('status'))
                <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
                    <strong class="font-bold">Success!</strong>
                    <span class="block sm:inline">{{ session('status') }}</span>
                </div>
            @endif

            <h1 class="text-2xl font-bold uppercase text-gray-700 dark:text-gray-200 mb-2">{{ $hero->name }}</h1>

            <form action="{{ route('heroes.update', ['id' => $hero->id]) }}" method="POST">
                @method('PATCH')
                @csrf

                <div class="flex flex-col space-y-3 dark:text-gray-300 mb-3">

                    <!-- Name -->
                    <div>
                        <label class="input-label mb-1">Name</label>
                        <input name="name" class="input {{ $errors->has('name') ? 'has-error' : '' }}" type="text" value="{{ old('name') ?? $hero->name }}">
                        @error('name')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Gender -->
                    <div>
                        <label class="input-label mb-1">Gender</label>
                        <input name="gender" class="input {{ $errors->has('gender') ? 'has-error' : '' }}" type="text" value="{{ old('gender') ?? $hero->gender }}">
                        @error('gender')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Mass -->
                    <div>
                        <label class="input-label mb-1">Mass (kg)</label>
                        <input name="mass" class="input {{ $errors->has('mass') ? 'has-error' : '' }}" type="number" value="{{ old('mass') ?? $hero->mass }}">
                        @error('mass')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Height -->
                    <div>
                        <label class="input-label mb-1">Height (cm)</label>
                        <input name="height" class="input {{ $errors->has('height') ? 'has-error' : '' }}" type="number" value="{{ old('height') ?? $hero->height }}">
                        @error('height')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Hair color -->
                    <div>
                        <label class="input-label mb-1">Hair color</label>
                        <input name="hair_color" class="input {{ $errors->has('hair_color') ? 'has-error' : '' }}" type="text" value="{{ old('hair_color') ?? $hero->hair_color }}">
                        @error('hair_color')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Birth year -->
                    <div>
                        <label class="input-label mb-1">Birth year</label>
                        <input name="birth_year" class="input {{ $errors->has('birth_year') ? 'has-error' : '' }}" type="text" value="{{ old('birth_year') ?? $hero->birth_year }}">
                        @error('birth_year')
                            <div class="text-red-500">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class="flex justify-end">
                    <a href="{{ route('heroes.get', ['hero' => $hero->id]) }}" class="px-3 py-2 text-base dark:text-gray-100">Back</a>
                    <button type="submit" class="btn px-3 py-2 text-base">Save</button>
                </div>
            </form>

        </div>
    </div>
</x-app-layout>

resources/views/heroes/get.blade.php
<x-app-layout>
    @section('title')
        {{ $hero->name }}
    @endsection

    <div class="py-3 md:py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="flex justify-between items-center mb-2">
                <h1 class="text-2xl font-bold uppercase text-gray-700 dark:text-gray-200">{{ $hero->name }}</h1>
                <a href="{{ route('heroes.edit', ['hero' => $hero->id]) }}" class="btn text-base px-3 py-1.5">Edit</a>
            </div>
            <div class="flex flex-col space-y-1 bg-white dark:bg-gray-800 dark:text-gray-300 rounded-md p-4">
                <div>
                    <span class="font-bold">Gender:</span>
                    {{ $hero->gender }}
                </div>
                <div>
                    <span class="font-bold">Mass (kg):</span>
                    {{ $hero->mass }}
                </div>
                <div>
                    <span class="font-bold">Height (cm):</span>
                    {{ $hero->height }}
                </div>
                <div>
                    <span class="font-bold">Hair color:</span>
                    {{ $hero->hair_color }}
                </div>
                <div>
                    <span class="font-bold">Birth year:</span>
                    {{ $hero->birth_year }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/heroes/index.blade.php
<x-app-layout>
    @section('title')
        Heroes
    @endsection

    <div class="py-3 md:py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <livewire:heroes-table />
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title') | {{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        @livewireStyles

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100 dark:bg-gray-750">
            @include('layouts.navigation')
            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white dark:bg-gray-900 dark:text-white border-b border-gray-100 dark:border-gray-900">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('heroes.index') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-blue-500 dark:text-red-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('heroes.index')" :active="request()->routeIs('heroes.*')">
                        {{ __('Heroes') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <button id="toggle-theme" class="btn sm:mr-3">Change side</button>

                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 dark:text-gray-100 hover:text-gray-700 dark:hover:text-gray-300 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('heroes.index')" :active="request()->routeIs('heroes.*')">
                {{ __('Heroes') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <button id="toggle-theme-responsive" class="btn mb-2">Change side</button>
                <div class="font-medium text-base text-gray-800 dark:text-gray-100">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500 dark:text-gray-100">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/livewire/heroes-table.blade.php
<div class="flex flex-col space-y-2">
    <div class="flex justify-between items-center">

        <!-- Name search imput -->
        <div class="w-full md:w-1/3 pr-3 mb-3 md:mb-0">
            <label class="input-label mb-1">
                Name
            </label>
            <input wire:model.debounce.500ms="name" name="name" class="input" type="text" placeholder="Search by name...">
        </div>

        <!-- Gender dropdown -->
        <div class="w-full md:w-1/3 pl-3 mb-3 md:mb-0">
            <label class="input-label" for="gender-input">
                Gender
            </label>
            <div class="relative">
                <select wire:model="gender" name="gender" class="input" id="gender-input">
                    <option value="all">all</option>
                    @foreach ($genders as $gender)
                        <option wire:click="$set('gender', $gender')" value="{{ $gender }}">{{ $gender }}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>

    <div class="overflow-x-auto">
        <table class="min-w-max w-full table-auto shadow-md rounded-lg overflow-hidden bg-white dark:bg-gray-800">
            @if (!$heroes->isEmpty())
                <thead>
                <tr class="bg-gray-200 dark:bg-gray-900 text-gray-600 dark:text-gray-100 uppercase text-sm leading-normal">
                    <th class="py-3 px-6 text-left">ID</th>
                    <th class="py-3 px-6 text-left">Name</th>
                    <th class="py-3 px-6 text-center">Gender</th>
                    <th class="py-3 px-6 text-center">Mass (kg)</th>
                    <th class="py-3 px-6 text-center">Height (cm)</th>
                    <th class="py-3 px-6 text-center">Hair color</th>
                    <th class="py-3 px-6 text-center">Birth year</th>
                    <th class="py-3 px-6 text-center">Options</th>
                </tr>
                </thead>
            @endif
            <tbody class="text-gray-600 text-sm font-light">

            @forelse ($heroes as $hero)
                <tr class="border-b border-gray-200 dark:border-gray-900 hover:bg-gray-100 dark:hover:bg-gray-900 dark:text-gray-100">
                    <td class="py-3 px-6 text-left whitespace-nowrap">
                        {{ $hero->id }}
                    </td>
                    <td class="py-3 px-6 text-left">
                        {{ $hero->name }}
                    </td>
                    <td class="py-3 px-6 text-center">
                            <span
                                class="badge {{ $hero->isMale() ? 'bg-blue-200 text-blue-600' : ($hero->isFemale() ? 'bg-pink-200 text-pink-600' : 'bg-gray-200 text-gray-600') }}">
                                {{ $hero->gender }}
                            </span>
                    </td>
                    <td class="py-3 px-6 text-center">
                        {{ $hero->mass ?? '-' }}
                    </td>
                    <td class="py-3 px-6 text-center">
                        {{ $hero->height ?? '-' }}
                    </td>
                    <td class="py-3 px-6 text-center">
                        {{ $hero->hair_color }}
                    </td>
                    <td class="py-3 px-6 text-center">
                        {{ $hero->birth_year ?? '-' }}
                    </td>
                    <td>
                        <div class="flex justify-center items-center">
                            <a href="{{ route('heroes.get', ['hero' => $hero->id]) }}" class="w-4 mx-1 transform hover:text-blue-500 dark:hover:text-red-500 hover:scale-110 cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                                </svg>
                            </a>
                            <a href="{{ route('heroes.edit', ['hero' => $hero->id]) }}" class="w-4 mx-1 transform hover:text-blue-500 dark:hover:text-red-500 hover:scale-110 cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/>
                                </svg>
                            </a>
                        </div>
                    </td>
                </tr>
            @empty
                <h1 class="text-lg font-bold text-gray-800 dark:text-gray-200">Heroes not found!</h1>
            @endforelse
            </tbody>
        </table>
    </div>
    @if (!$heroes->isEmpty())
        {{ $heroes->links('livewire.pagination.tailwind') }}
    @endif
</div>